# ----------------------------------------------------------------------------------------------------------------------
# 命名空间
# ----------------------------------------------------------------------------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: chth-kebernetes

---

