# ----------------------------------------------------------------------------------------------------------------------
# Eureka
# ----------------------------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: chth-kebernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chth-kebernetes
      node: eureka
  template:
    metadata:
      name: eureka
      namespace: chth-kebernetes
      labels:
        app: chth-kebernetes
        node: eureka
    spec:
      volumes:
      - name: log
        hostPath:
          path: /var/log/chth-eureka/
      - name: logstash
        configMap:
          name: chth
          items:
          - key: logstash-eureka
            path: eureka.conf
      containers:
      - name: eureka
        image: 192.168.99.115/chth/springboot-springcloud-docker-kebernetes-eureka:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: log
          mountPath: /chth
        - name: logstash
          mountPath: /config
        ports:
        - containerPort: 1668
      - name: eureka-logstash
        image: 192.168.99.115/docker-hub/logstash:5.6.14
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: log
          mountPath: /var/log/chth-eureka/
        - name: logstash
          mountPath: /config
        command:
        - "logstash"
        - "-f"
        - "/config/eureka.conf"

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: chth-kebernetes
spec:
  selector:
    app: chth-kebernetes
    node: eureka
  type: LoadBalancer
  ports:
  - name: main
    port: 1668
    targetPort: 1668
    nodePort: 1668
