# ----------------------------------------------------------------------------------------------------------------------
# Service - Account
# ----------------------------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: chth-kebernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chth-kebernetes
      node: front
  template:
    metadata:
      name: service
      namespace: chth-kebernetes
      labels:
        app: chth-kebernetes
        node: front
    spec:
      volumes:
      - name: log
        hostPath:
          path: /var/log/chth-front/
      - name: logstash
        configMap:
          name: chth
          items:
          - key: logstash-front
            path: front.conf
      containers:
      - name: service
        image: 192.168.99.115/chth/springboot-springcloud-docker-kebernetes-front:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: log
          mountPath: /chth
        ports:
        - containerPort: 1669
      - name: consumer-logstash
          image: 192.168.99.115/docker-hub/logstash:5.6.14
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: log
            mountPath: /var/log/chth-front/
          - name: logstash
            mountPath: /config
          command:
          - "logstash"
          - "-f"
          - "/config/front.conf"
---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: chth-kebernetes
spec:
  selector:
    app: chth-kebernetes
    node: front
  type: LoadBalancer
  ports:
  - name: main
    port: 1669
    targetPort: 1669
    nodePort: 1669
