# ----------------------------------------------------------------------------------------------------------------------
# Service - Account
# ----------------------------------------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  namespace: chth-kebernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chth-kebernetes
      node: service
  template:
    metadata:
      name: service
      namespace: chth-kebernetes
      labels:
        app: chth-kebernetes
        node: service
    spec:
      volumes:
      - name: log
        hostPath:
          path: /var/log/chth-service/
      - name: logstash
        configMap:
          name: chth
          items:
          - key: logstash-service
            path: service.conf
      containers:
      - name: service
        image: 192.168.99.115/chth/springboot-springcloud-docker-kebernetes-service:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: log
          mountPath: /chth
        ports:
        - containerPort: 1667
        env:
        - name: CHTH_FIRST_NAME
          value: cheng
      - name: service-logstash
        image: 192.168.99.115/docker-hub/logstash:5.6.14
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: log
          mountPath: /var/log/chth-service/
        - name: logstash
          mountPath: /config
        command:
        - "logstash"
        - "-f"
        - "/config/service.conf"
---

apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: chth-kebernetes
spec:
  selector:
    app: chth-kebernetes
    node: service
  type: LoadBalancer
  ports:
  - name: main
    port: 1667
    targetPort: 1667
    nodePort: 1667
